"use client";
import { Box } from "@chakra-ui/react";
import Providers from "./providers";

import "@fontsource/fira-sans/300.css";
import "@fontsource/fira-sans/400.css";
import "@fontsource/fira-sans/500.css";
import "@fontsource/fira-sans/600.css";
import "@fontsource/playfair-display/variable.css";
import Footer from "~organisms/footer/Footer";
import TopPanel from "~organisms/topPanel/TopPanel";
import { worker } from "~mocks/browser";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

async function enableMocking() {
  if (process.env.NODE_ENV !== "development") {
    return;
  }

  // `worker.start()` returns a Promise that resolves
  // once the Service Worker is up and ready to intercept requests.
  return worker.start({ onUnhandledRequest: "bypass" });
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopPanel />
          <Box m="10vh auto">{children}</Box>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

enableMocking();
