"use client";
import Providers from "./providers";

import "@fontsource/fira-sans/400.css";
import "@fontsource/fira-sans/500.css";
import "@fontsource/fira-sans/600.css";
import "@fontsource/playfair-display/variable.css";
import Footer from "~organisms/footer/Footer";
import TopPanel from "~organisms/topPanel/TopPanel";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopPanel />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
